CREATE DATABASE filme;

CREATE TABLE filmes (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
descricao VARCHAR(1000) NOT NULL,
ano INT);

CREATE TABLE filmes2 (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
descricao VARCHAR(1000) NOT NULL,
ano INT);

INSERT INTO `filme`.`filmes` (`id`, `nome`, `descricao`, `ano`) VALUES ('1', 'Capitão América - O primeiro vingador', 'Steve Rogers é um jovem que aceitou ser voluntário em experiências para cirar um supersoldado. Os militares conseguem transformá-lo em uma arma humana, mas percebem que o supersoldado é valioso demais para colocá-lo em risco na luta contra os nazistas', '2011');
INSERT INTO `filme`.`filmes` (`id`, `nome`, `descricao`, `ano`) VALUES ('2', 'Capitã Marvel', 'Este filme é uma aventura totalmente nova de um período nunca visto na história do UCM que acompanha a jornada de Carol Danvers, conforme ela se torna uma das mais poderosas do universo. Enquanto uma guerra galática entre duas raças alienígenas chega à Terra, Danvers se vê junto a um pequeno grupo de aliados bem no meio da ação.', '2019');
INSERT INTO `filme`.`filmes` (`id`, `nome`, `descricao`, `ano`) VALUES ('3', 'Homem de Ferro', 'Quando é capturado em território inimigo, o genial magnata Tony Stark constrói uma armadura de alta tecnologia para escapar. Agora, ele tem a missão de salvar o mundo como um herói que não nasceu.', '2008');
INSERT INTO `filme`.`filmes` (`id`, `nome`, `descricao`, `ano`) VALUES ('4', 'O Incrível Hulk', 'O cientista Bruce Banner se esconde no Brasil enquanto busca desesperadamente a cura da mutação que o transforma em um monstro incontrolável. Só assim ele poderá novamente levar uma vida normal e ficar ao lado da mulher que ama. Porém, durante este processo, ele precisa lutar contra o Abominável, um novo inimigo que quer capturá-lo.', '2008');
INSERT INTO `filme`.`filmes` (`id`, `nome`, `descricao`, `ano`) VALUES ('5', 'Homem de Ferro 2', 'Em um mundo ciente da existência do Homem de Ferro, o inventor bilionário Tony Stark sofre pressão de todos os lados para compartilhar sua tecnologia com as forças armadas. Ele resiste para divulgar os segredos de sua inigualável armadura, com medo de que estas informações caiam nas mãos erradas. Com a bela Pepper Potts e o amigo \"Rhodey\" Rhodes ao seu lado, Tony precisa forjar novas alianças e confrontar um inimigo poderoso.', '2010');
INSERT INTO `filme`.`filmes` (`id`, `nome`, `descricao`, `ano`) VALUES ('6', 'Thor', 'Como filho de Odin, rei dos deuses nórdicos, Thor logo herdará o trono de Asgard de seu idoso pai. Porém, no dia de sua coroação, Thor reage com brutalidade quando os inimigos dos deuses entram no palácio violando o tratado. Como punição, Odin manda Thor para a Terra. Enquanto seu irmão Loki conspira em Asgard, Thor, agora sem seus poderes, enfrenta sua maior ameaça.', '2011');
INSERT INTO `filme`.`filmes` (`id`, `nome`, `descricao`, `ano`) VALUES ('7', 'Os Vingadores', 'Loki, o irmão de Thor, ganha acesso ao poder ilimitado do cubo cósmico ao roubá-lo de dentro das instalações da S.H.I.E.L.D. Nick Fury, o diretor desta agência internacional que mantém a paz, logo reúne os únicos super-heróis que serão capazes de defender a Terra de ameaças sem precedentes. Homem de Ferro, Capitão América, Hulk, Thor, Viúva Negra e Gavião Arqueiro formam o time dos sonhos de Fury, mas eles precisam aprender a colocar os egos de lado e agir como um grupo em prol da humanidade.', '2012');
INSERT INTO `filme`.`filmes` (`id`, `nome`, `descricao`, `ano`) VALUES ('8', 'Homem de Ferro 3', 'Depois de um inimigo reduzir o mundo de Tony Stark a destroços, o Homem de Ferro precisa aprender a confiar em seus instintos para proteger aqueles que ama, especialmente sua namorada, e lutar contra seu maior medo: o fracasso.', '2013');
INSERT INTO `filme`.`filmes` (`id`, `nome`, `descricao`, `ano`) VALUES ('9', 'Thor: O Mundo Escuro', 'Thor precisa contar com a ajuda de seus companheiros e até de seu traiçoeiro irmão Loki em um plano audacioso para salvar o universo. Entretanto, os caminhos de Thor se cruzam com Jane Foster e, dessa vez, a vida dela está realmente em perigo.', '2013');
INSERT INTO `filme`.`filmes` (`id`, `nome`, `descricao`, `ano`) VALUES ('10', 'Capitão América: The Winter Soldier', 'Após os eventos catastróficos em Nova York com Os Vingadores, Steve Rogers, também conhecido como Capitão América, segue tentando se ajustar ao mundo moderno. Porém, quando um colega da agência S.H.I.E.L.D. é atacado, Steve se vê preso em uma rede de intrigas que ameaça colocar o mundo em risco. Em parceria com a Viúva Negra e Falcão, seu novo aliado, o Capitão América tem que enfrentar um misterioso e inesperado inimigo, o Soldado Invernal.', '2014');
INSERT INTO `filme`.`filmes2` (`id`, `nome`, `descricao`, `ano`) VALUES ('1', 'Guardiães da Galáxia', 'O aventureiro do espaço Peter Quill torna-se presa de caçadores de recompensas depois que rouba a esfera de um vilão traiçoeiro, Ronan. Para escapar do perigo, ele faz uma aliança com um grupo de quatro extraterrestres. Quando Quill descobre que a esfera roubada possui um poder capaz de mudar os rumos do universo, ele e seu grupo deverão proteger o objeto para salvar o futuro da galáxia.', '2014');
INSERT INTO `filme`.`filmes2` (`id`, `nome`, `descricao`, `ano`) VALUES ('2', 'Guardiães da Galáxia Vol 2', 'Os Guardiões da Galáxia lutam para manter sua nova família unida enquanto desvendam os mistérios sobre o verdadeiro pai de Peter Quill.', '2017');
INSERT INTO `filme`.`filmes2` (`id`, `nome`, `descricao`, `ano`) VALUES ('3', 'Vingadores: Era do Ultron', 'Ao tentar proteger o planeta de ameaças, Tony Stark constrói um sistema de inteligência artificial que cuidaria da paz mundial. O projeto acaba dando errado e gera o nascimento do Ultron. Com o destino da Terra em jogo, Capitão América, Homem de Ferro, Thor, Hulk, Viúva Negra e Gavião Arqueiro terão que se unir para mais uma vez salvar a raça humana da extinção.', '2015');
INSERT INTO `filme`.`filmes2` (`id`, `nome`, `descricao`, `ano`) VALUES ('4', 'Ant-Man', 'Embora não pareça ser o herói típico, sua agilidade física, seu conhecimento sobre tecnologia e o forte caráter moral tornam Scott um candidato ideal para usar o traje do Homem-Formiga.', '2015');
INSERT INTO `filme`.`filmes2` (`id`, `nome`, `descricao`, `ano`) VALUES ('5', 'Capitão América: Guerra Civil', 'Depois do ataque de Ultron, os políticos decidem controlar os Vingadores, já que suas ações afetam toda a humanidade. A decisão coloca o Capitão América em rota de colisão com o Homem de Ferro.', '2016');
INSERT INTO `filme`.`filmes2` (`id`, `nome`, `descricao`, `ano`) VALUES ('6', 'Homem-Aranha: Homecoming', 'Depois de lutar ao lado dos Vingadores, chegou a hora do jovem Peter Parker voltar para casa em Nova York ao lado de sua tia May. Sob o olhar atento do mentor Tony Stark, Peter começa a abraçar sua nova identidade como Homem-Aranha e combate diariamente pequenos crimes nas redondezas. Ele acredita que encontrou a missão de sua vida quando o terrível vilão Abutre surge ameaçando a cidade. O problema é que a tarefa não será tão fácil como ele imaginava.', '2017');
INSERT INTO `filme`.`filmes2` (`id`, `nome`, `descricao`, `ano`) VALUES ('7', 'Pantera Negra', 'Conheça a história de T\'Challa, príncipe do reino de Wakanda, que perde o seu pai e viaja para os Estados Unidos, onde tem contato com os Vingadores. Entre as suas habilidades estão a velocidade, inteligência e os sentidos apurados.', '2018');
INSERT INTO `filme`.`filmes2` (`id`, `nome`, `descricao`, `ano`) VALUES ('8', 'Viúva Negra', 'Ao nascer, a Viúva Negra, então conhecida como Natasha Romanova, é entregue à KGB, que a prepara para se tornar sua agente suprema. Porém, o seu próprio governo tenta matá-la quando a União Soviética se desfaz.', '2021');
INSERT INTO `filme`.`filmes2` (`id`, `nome`, `descricao`, `ano`) VALUES ('9', 'Doutor Estranho', 'Após sua carreira ser destruída, um brilhante, porém arrogante, cirurgião ganha uma nova chance em sua vida quando um feiticeiro o treina para se tornar o Mago Supremo.', '2016');
INSERT INTO `filme`.`filmes2` (`id`, `nome`, `descricao`, `ano`) VALUES ('10', 'Thor: Ragnarok', 'Após anos afastado, Thor retorna para casa e descobre que seu pai, Odin, rei de Asgard, está desaparecido. Após encontrá-lo, ele toma conhecimento de sua irmã mais velha, Hela, a poderosa e implacável deusa da morte. Com o auxílio de Loki, ele enfrenta Hela, mas durante a batalha, Thor acaba preso em Sakaar, um planeta do outro lado do universo. Agora, ele precisa correr contra o tempo para voltar a Asgard e impedir o Ragnarok, a destruição de seu mundo.', '2017');

